version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tb-postgres
    restart: always
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_USER: thingsboard
      POSTGRES_PASSWORD: thingsboard
    volumes:
      - tb-postgres-data:/var/lib/postgresql/data
  thingsboard:
    image: thingsboard/tb-postgres:3.6.3
    container_name: thingsboard
    depends_on:
      - postgres
    restart: always
    ports:
      - "8080:9090"
    environment:
      TB_QUEUE_TYPE: in-memory
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      SPRING_DATASOURCE_USERNAME: thingsboard
      SPRING_DATASOURCE_PASSWORD: thingsboard
    volumes:
      - tb-data:/data
      - tb-logs:/var/log/thingsboard

volumes:
  tb-postgres-data:
  tb-data:
  tb-logs:
